import {
  BadgeCheck,
  BarChart3,
  Bell,
  Brain,
  Briefcase,
  Building2,
  CalendarDays,
  ClipboardList,
  Cloud,
  Code2,
  Compass,
  Fingerprint,
  GraduationCap,
  HeartPulse,
  Layers,
  Megaphone,
  MessagesSquare,
  Network,
  School,
  ShieldCheck,
  Sparkles,
  Store,
  Target,
  UserRound,
  Users,
  Wrench,
  type LucideIcon,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  compass: Compass,
  graduation: GraduationCap,
  target: Target,
  code: Code2,
  network: Network,
  users: Users,
  user: UserRound,
  briefcase: Briefcase,
  calendar: CalendarDays,
  clipboard: ClipboardList,
  bell: Bell,
  chart: BarChart3,
  store: Store,
  heart: HeartPulse,
  wrench: Wrench,
  brain: Brain,
  message: MessagesSquare,
  school: School,
  megaphone: Megaphone,
  building: Building2,
  fingerprint: Fingerprint,
  shield: ShieldCheck,
  badge: BadgeCheck,
  layers: Layers,
  cloud: Cloud,
};

export function getServiceIcon(name?: string): LucideIcon {
  if (!name) return Sparkles;
  return ICONS[name] ?? Sparkles;
}
